name: tests

#on: [ pull_request, workflow_dispatch ]
on: [ push, workflow_dispatch ]

jobs:

  checks:

    runs-on: cirrusci/flutter:3.0.5

    env:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Linter
        run: bin/lint.sh

      - name: Tests
        run: bin/test.sh