name: tests

on: [ pull_request, workflow_dispatch ]
#on: [ push, workflow_dispatch ]

jobs:

  checks:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        channel: [ stable ]

    env:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}
          cache: true
      #          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
      #          cache-path:
      #            ${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch: # optional, change this to specify the cache pat

      - name: Install dependencies
        run: flutter pub get

      - name: Linter
        run: bin/lint.sh

      - name: Tests
        run: flutter test --reporter=github